# Sample config for haystack storage
[servers]
[servers.alpha]
endpoint = "127.0.0.1:55533"

[servers.beta]
endpoint = "127.0.0.2:55533"

#etc, may be we will add something else
[api]
[api.alpha]
endpoint = "127.0.0.1:8080"

[api.beta]
endpoint = "127.0.0.3:8080"
