// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: haystack.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	HaystackStorage_GetUid_FullMethodName = "/haystack.HaystackStorage/GetUid"
)

// HaystackStorageClient is the client API for HaystackStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HaystackStorageClient interface {
	GetUid(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Uid, error)
}

type haystackStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewHaystackStorageClient(cc grpc.ClientConnInterface) HaystackStorageClient {
	return &haystackStorageClient{cc}
}

func (c *haystackStorageClient) GetUid(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Uid, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Uid)
	err := c.cc.Invoke(ctx, HaystackStorage_GetUid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HaystackStorageServer is the server API for HaystackStorage service.
// All implementations must embed UnimplementedHaystackStorageServer
// for forward compatibility
type HaystackStorageServer interface {
	GetUid(context.Context, *emptypb.Empty) (*Uid, error)
	mustEmbedUnimplementedHaystackStorageServer()
}

// UnimplementedHaystackStorageServer must be embedded to have forward compatible implementations.
type UnimplementedHaystackStorageServer struct {
}

func (UnimplementedHaystackStorageServer) GetUid(context.Context, *emptypb.Empty) (*Uid, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUid not implemented")
}
func (UnimplementedHaystackStorageServer) mustEmbedUnimplementedHaystackStorageServer() {}

// UnsafeHaystackStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HaystackStorageServer will
// result in compilation errors.
type UnsafeHaystackStorageServer interface {
	mustEmbedUnimplementedHaystackStorageServer()
}

func RegisterHaystackStorageServer(s grpc.ServiceRegistrar, srv HaystackStorageServer) {
	s.RegisterService(&HaystackStorage_ServiceDesc, srv)
}

func _HaystackStorage_GetUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HaystackStorageServer).GetUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HaystackStorage_GetUid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HaystackStorageServer).GetUid(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HaystackStorage_ServiceDesc is the grpc.ServiceDesc for HaystackStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HaystackStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "haystack.HaystackStorage",
	HandlerType: (*HaystackStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUid",
			Handler:    _HaystackStorage_GetUid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "haystack.proto",
}
