# SS endpoints
[SS]
[SS.alpha]
endpoint = "127.0.0.1:55533"

[SS.beta]
endpoint = "127.0.0.2:55533"

# API gateway endpoints
[GW]
[GW.alpha]
endpoint = "127.0.0.1:8080"

[GW.beta]
endpoint = "127.0.0.3:8080"
